Ingest the remaining entities and relationships
JupiterOne/graph-artifactory pull request #5
Opened 2020-09-03 17:02 UTC by neurovelho

This PR includes the remaining of the high value entities and relationships as discussed in the [issue thread](https://github.com/JupiterOne/graph-artifactory/issues/3).

Kindly let us know if something needs to be changed.

2020-09-03 17:06 UTC, neurovelho commented
Pinging @aiwilliams @ndowmon @austinkelleher

2020-09-04 02:33 UTC, ndowmon requested changes
@neurovelho Thanks for all the work here! All the new entities and relationships look really good.

I peppered some requests throughout for you to review. In particular, I'd like you to take another look at the `artifactory_permissions` entities and relationships. Let me know if any of my comments don't make sense and we can discuss in more detail.

2020-09-04 02:33 UTC, ndowmon commented on src/constants.ts
> +  },
Actually, read comments in `/permissions.ts`. Not sure there should be _any_ `DENIES` relationships.

2020-09-04 02:33 UTC, ndowmon commented on src/steps/permissions.ts
> +    dependsOn: ['fetch-users', 'fetch-repositories', 'fetch-builds'],
should also depend on `fetch-groups`

2020-09-04 02:33 UTC, ndowmon commented on src/steps/permissions.ts
> +  await jobState.addEntity(permissionEntity);
Looks like this code is adding two `artifactory_permission` entities for every permission. There should be just _one_ `artifactory_permission` entity created. That single entity should have relationships to both users _and_ groups.

2020-09-04 02:33 UTC, ndowmon commented on src/steps/permissions.ts
> +function constructPermissionsMap(
Per artifactory [docs](https://www.jfrog.com/confluence/display/JFROG/Permissions), there can also be release bundle permissions, destination permissions, and pipeline permissions, PLUS "global permissions". Can you pull those additional permission targets in this function? I realize that some of those can't be used to target existing entities, but can you add code comments to implement others when they are implemented in the future?

2020-09-04 02:33 UTC, ndowmon commented on src/steps/permissions.ts
> +async function createPermissionBuildAllowsRelationships(
Jfrog docs discussing **include** and **exclude** patterns seem to indicate that both the statements are used to pattern match permission targets that are allowed by a given permission. I don't think the **exclude** pattern is actually a `DENIES` statement in reality.

I would instead suggest creating only `ALLOWS` statements for permissions targets that _do_ match the `include-pattern` and _do not_ match the `exclude-pattern`.

Also, I notice that artifactory exposes a pattern matching API - it would be better to use a matcher provided by the vendor than a nodejs utility. See https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API

```
Usage: GET /api/search/pattern?pattern=repo-key:this/is/a/*pattern*.war
```

2020-09-04 02:33 UTC, ndowmon commented on src/types.ts
> +      };
I haven't used the API, but it seems to me that `permission.repo` also has the `include-patterns` and `exclude-patterns` properties.

2020-09-04 02:33 UTC, ndowmon commented on src/types.ts
> +    'exclude-patterns': string[];
You should enumerate all of the permission target types, including `destinations`, `pipeline-sources`, `release-bundles`, and possibly `global` if it exists.

2020-09-04 17:28 UTC, neurovelho commented on src/steps/access.ts
> +    relationships: [relationships.ACCOUNT_HAS_ACCESS_TOKEN],
Looks like the admin can only create what's called admin access token, however it looks like it's actually possible to create regular access tokens that target a specific user using the rest api, so we'll change this.

2020-09-04 17:34 UTC, neurovelho commented on src/steps/repositories.ts
> +
Yeah I'm not too excited about this matcher either, I think it would be much better if we could just roll with one type.

2020-09-04 17:34 UTC, neurovelho commented on src/steps/index.test.ts
> +    await fetchBuilds(context);
Looks like we missed it, good catch.

2020-09-04 17:37 UTC, neurovelho commented on src/client.ts
> +      this.withBaseUri('artifactory/api/v2/security/permissions'),
These are the docs to the v2 api: https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API+V2, so it only contains a few extending endpoints. We used the v2 here because the response format looked a bit better.

2020-09-04 17:48 UTC, neurovelho commented on src/steps/pipelineSources.ts
> +    relationships: [relationships.ACCOUNT_HAS_PIPELINE_SOURCE],
Well this is where things get interesting :smile:

So repositoryFullName here targets a git repo, in this case a just a dummy repo I created which contains some pipeline configuration. It's not related to an Artifactory repository.

Will definitely take a second look and see if there's a way to map this entity with other entities.

2020-09-04 17:56 UTC, neurovelho commented on src/steps/permissions.ts
> +  await jobState.addEntity(permissionEntity);
We were going by this comment here: https://github.com/JupiterOne/graph-artifactory/issues/3#issuecomment-678661547, but seeing as the response contains both users and groups, it would make more sense if we had both users and groups in the entity.

2020-09-04 17:58 UTC, neurovelho commented on src/steps/permissions.ts
> +function constructPermissionsMap(
The api documentation seems to indicate that only repository, build and releaseBundle are available, though it could be that it's outdated :thinking: 

We'll definitely see if it's possible to add the rest.

2020-09-04 18:12 UTC, ndowmon commented on src/steps/pipelineSources.ts
> +    relationships: [relationships.ACCOUNT_HAS_PIPELINE_SOURCE],
Understood - seems more complex than I initially expected, if it ends up not being simple to implement a direct relationship you can disregard.

2020-09-04 18:52 UTC, ndowmon commented on src/client.ts
> +    if (['ANY', 'ANY LOCAL', 'ANY REMOTE'].includes(key)) {
Makes sense to me. If these are special, though, I would suggest using a different `_class` and `_type`. Probably `Group` and `artifactory_repository_group`, respectively. That way you won't have to filter them out when calling `iterateRepositoryArtifacts`.

2020-09-04 18:53 UTC, ndowmon commented on src/steps/permissions.ts
> +  await jobState.addEntity(permissionEntity);
Just to clarify - you mean both users and groups ~~in~~ _related to_ the entity, correct?

2020-09-04 20:52 UTC, ndowmon commented on src/steps/repositories.ts
> +
Spoke with @erichs about this. It really stinks that the API appears to only reliably return `folder` and `uri` properties, no additiona metadata: 
```
{
  "folder": false,
  "uri": "https://codeworkr.jfrog.io/artifactory/docker-repo/hello-world/1.1.1/sha256__bf756fb1ae65adf866bd8c456593cd24beb6a0a061dedf42b26a993176745f6b",
}
```

Since there are no other properties we can rely on, it doesn't seem like a great idea for us to add any custom matcher in our code (following the philosophy that we at J1 _only_ ingest the state of a target system, and don't build additional logic).

As long as you are pulling the `projectType` property on `artifactory_repository` entities, we can create J1QL like the following, which is good enough for now:

```
// look for maven builds
find 
  artifactory_repository that has 
  artifactory_artifact 
where 
  artifactory_repository.packageType = 'Maven'
```

2020-09-07 10:20 UTC, neurovelho commented on src/steps/permissions.ts
> +  await jobState.addEntity(permissionEntity);
Yes, that's right.

2020-09-09 15:09 UTC, neurovelho commented
Alrighty, we've implemented the changes you requested @ndowmon.

There's however a few complications though:

- We implemented the user -> assigned -> access token relationship, however it looks like no matter what you do in the dashboard or API, the access tokens simply won't show up in the api/token response -- only the admin tokens do. Sadly this seems like a regular occurrence with this API.
- After trying out multiple things it seems like API only returns repository, build and releaseBundle permissions:

  **Release bundle** permission is difficult/impossible to implement because they aren’t available during the trial.

  **Pipeline permissions** can’t seem to be fetched even after we create them in the permission using JFrog admin dashboard, the API simply isn’t returning those for some reason.

  **Destination permissions** - we aren’t exactly sure what these represent, we don’t see additional field(s) for setting this on the permission setting page nor does the API returns anything about them.
- The pattern matching endpoint can only be used for artifacts, nothing else. That means that when we're matching include/exclude patterns for repositories and builds we pretty much have to use the external library for matching.

2020-09-09 16:20 UTC, ndowmon approved these changes
Thanks for making the requested changes! This integration definitely looks ready for deployment to me.

I commented a few small requests but we can easily open new github issues for those and fix in the future.

2020-09-09 16:20 UTC, ndowmon commented on src/steps/permissions.ts
> +    (buildEntity) => `${permissionEntity._key}|allows|${buildEntity._key}`,
Not a big deal since it's functionally correct, but here it should be `permissionEntity`.

2020-09-09 16:20 UTC, ndowmon commented on src/steps/permissions.ts
> +      relationships.PERMISSION_ALLOWS_REPOSITORY_GROUP,
Cool, thanks for adding this!

2020-09-09 16:20 UTC, ndowmon commented on src/steps/index.test.ts
> +    await fetchPermissions(context);
Thanks for adding. Not necessary now, but let's add a GH issue to add an `expect` statement for permissions here.

2020-09-10 12:32 UTC, neurovelho commented on src/steps/permissions.ts
> +    (buildEntity) => `${permissionEntity._key}|allows|${buildEntity._key}`,
Did you mean `repositoryEntity`? In any case, I renamed it since it was bothering me too much :slightly_smiling_face:.

2020-09-10 13:33 UTC, ndowmon commented on src/steps/permissions.ts
> +    (buildEntity) => `${permissionEntity._key}|allows|${buildEntity._key}`,
Yes! Thanks.

2020-09-10 14:22 UTC, ndowmon approved these changes
Thanks @neurovelho. This is a great integration!

2020-09-10 14:22 UTC, merged